config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :summaries
  resources :articleinterns
  resources :bing_articles
  resources :gosearts
  resources :media
  resources :factiva_articles
  resources :articles
  resources :key_words do
    get 'keyword_posts/:id', to: 'key_words#keyword_posts', as: 'keyword_posts'
    collection do
      post :import
    end
  end
  root 'static#home'
  devise_for :users

  get 'static/test_post'
  get 'static/test'
  get 'static/test_webflow'
  post 'static/test_webhook'
  get 'static/scraper'
  get 'static/gosearts'
  get 'static/bing_news'
  get 'static/dashboard'
  get 'static/articleintern'
  get 'static/analyzer'
  get 'static/analyzer_new'
  get 'static/keyword_list'
  get 'static/article_creator'
  # test only

  get 'static/gosearts_test'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/bing_article.rb
class BingArticle < ApplicationRecord
  belongs_to :key_word
  validates :link, uniqueness: true
  has_one :summary,  dependent: :destroy
  def as_json(options = {})
    super(options.merge(include: { key_word: { only: :key_word } }))
  end
end

app/controllers/bing_articles_controller.rb
class BingArticlesController < ApplicationController
  before_action :set_bing_article, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token
  require 'open-uri'
  require 'text_analyzer'
  # GET /bing_articles or /bing_articles.json
  def index
    if params[:status]== "pending" || params[:status]== nil
      @articles_all = BingArticle.includes(:key_word).where(category_label: nil).order("created_at DESC")
      json_response = @articles_all.to_json
      render json: json_response
    elsif params[:status]== "published" 
      @articles_all = BingArticle.includes(:key_word).where(category_label: "published").order("created_at DESC")
      json_response =@articles_all.to_json
      render json: json_response
    elsif params[:status]== "archived" 
      @articles_all = BingArticle.includes(:key_word).where(category_label: "archived").order("created_at DESC")
      json_response =@articles_all.to_json
      render json: json_response
    else
      render json: {"not workin": 0}
    end
  end

  # GET /bing_articles/1 or /bing_articles/1.json
  def show
    keywords = count_words(@bing_article.link)
    @related_keywords = keywords[0]
    @array = keywords[1]
    @summary_text = @bing_article.summary ? @bing_article.summary.summary_text : 'Not summerised'
    render json: {
      related_keywords: @related_keywords,
      array: @array,
      summary: @summary_text
    }
  end

  # GET /bing_articles/new
  def new
    @bing_article = BingArticle.new
  end

  # GET /bing_articles/1/edit
  def edit
  end

  # POST /bing_articles or /bing_articles.json
  def create
    @bing_article = BingArticle.new(bing_article_params)

    respond_to do |format|
      if @bing_article.save
        format.html { redirect_to bing_article_url(@bing_article), notice: "Bing article was successfully created." }
        format.json { render :show, status: :created, location: @bing_article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bing_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bing_articles/1 or /bing_articles/1.json
  def update
    respond_to do |format|
      if @bing_article.update(bing_article_params)
        format.json { render :show, status: :ok, location: @bing_article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bing_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bing_articles/1 or /bing_articles/1.json
  def destroy
    @bing_article.destroy

    respond_to do |format|
      format.html { redirect_to bing_articles_url, notice: "Bing article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bing_article
      @bing_article = BingArticle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bing_article_params
      params.require(:bing_article).permit(:key_word_id, :title, :category_label, :score, :score_second, :published, :link)
    end

    def fetch_raw_text(url)
      begin 
        html = URI.open(url)
        doc = Nokogiri::HTML(html)
        text_elements = doc.css('h1, p')
        return text_elements.map(&:text).join(" ") # Return the concatenated text content of the selected elements
      rescue OpenURI::HTTPError, URI::InvalidURIError, Nokogiri::SyntaxError, SocketError, StandardError => error
        return "An error occurred: #{error}"
      end
    end

    def count_words(url)
      begin 
            html = URI.open(url)
            doc = Nokogiri::HTML(html)
          
            # Define the words you want to search for
            words_to_search = KeyWord.pluck(:key_word).freeze
          
            # Initialize a hash to store the word counts
            word_counts = Hash.new(0)
            array = []
            # Iterate over each word and count its occurrences
            words_to_search.each do |word|
              # Find all occurrences of the word in the webpage content
              occurrences =doc.text.scrub('').scan(/#{word}/i).size
              array << occurrences
              # Store the count in the hash
              word_counts[word] = occurrences
            end
          
            # Return the word counts
            return word_counts, array.sum

            rescue OpenURI::HTTPError => error
              word_counts 
              array =0
              return  word_counts, array
            rescue URI::InvalidURIError => error
              word_counts 
              array =0
              return  word_counts, array
            rescue Nokogiri::SyntaxError => error
              word_counts 
              array =0
              return  word_counts, array
            rescue SocketError => error
              word_counts 
              array =0
              return  word_counts, array
            rescue StandardError => error
              word_counts 
              array=0
              return  word_counts, array.
        
    
            end
          end 
        end 
      
end

app/helpers/bing_articles_helper.rb
module BingArticlesHelper
end

app/views/bing_articles/_bing_article.html.erb
<div id="<%= dom_id bing_article %>">
  <p>
    <strong>Key word:</strong>
    <%= bing_article.key_word_id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= bing_article.title %>
  </p>

  <p>
    <strong>Category label:</strong>
    <%= bing_article.category_label %>
  </p>

  <p>
    <strong>Score:</strong>
    <%= bing_article.score %>
  </p>

  <p>
    <strong>Score second:</strong>
    <%= bing_article.score_second %>
  </p>

  <p>
    <strong>Published:</strong>
    <%= bing_article.published %>
  </p>

  <p>
    <strong>Link:</strong>
    <%= bing_article.link %>
  </p>

</div>

app/views/bing_articles/_form.html.erb
<%= form_with(model: bing_article) do |form| %>
  <% if bing_article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bing_article.errors.count, "error") %> prohibited this bing_article from being saved:</h2>

      <ul>
        <% bing_article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :key_word_id, style: "display: block" %>
    <%= form.text_field :key_word_id %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :category_label, style: "display: block" %>
    <%= form.text_field :category_label %>
  </div>

  <div>
    <%= form.label :score, style: "display: block" %>
    <%= form.number_field :score %>
  </div>

  <div>
    <%= form.label :score_second, style: "display: block" %>
    <%= form.number_field :score_second %>
  </div>

  <div>
    <%= form.label :published, style: "display: block" %>
    <%= form.text_field :published %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_area :link %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bing_articles/edit.html.erb
<h1>Editing bing article</h1>

<%= render "form", bing_article: @bing_article %>

<br>

<div>
  <%= link_to "Show this bing article", @bing_article %> |
  <%= link_to "Back to bing articles", bing_articles_path %>
</div>

app/views/bing_articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bing articles <%= @count%></h1>

<div id="bing_articles">
  <% @bing_articles.each do |bing_article| %>
    <%= render bing_article %>
    <p>
      <%= link_to "Show this bing article", bing_article %>
    </p>
  <% end %>
</div>

<%= link_to "New bing article", new_bing_article_path %>

app/views/bing_articles/new.html.erb
<h1>New bing article</h1>

<%= render "form", bing_article: @bing_article %>

<br>

<div>
  <%= link_to "Back to bing articles", bing_articles_path %>
</div>

app/views/bing_articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bing_article %>

<div>
  <%= link_to "Edit this bing article", edit_bing_article_path(@bing_article) %> |
  <%= link_to "Back to bing articles", bing_articles_path %>

  <%= button_to "Destroy this bing article", @bing_article, method: :delete %>
</div>