config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :summaries
  resources :articleinterns
  resources :bing_articles
  resources :gosearts
  resources :media
  resources :factiva_articles
  resources :articles
  resources :key_words do
    get 'keyword_posts/:id', to: 'key_words#keyword_posts', as: 'keyword_posts'
    collection do
      post :import
    end
  end
  root 'static#home'
  devise_for :users

  get 'static/test_post'
  get 'static/test'
  get 'static/test_webflow'
  post 'static/test_webhook'
  get 'static/scraper'
  get 'static/gosearts'
  get 'static/bing_news'
  get 'static/dashboard'
  get 'static/articleintern'
  get 'static/analyzer'
  get 'static/analyzer_new'
  get 'static/keyword_list'
  get 'static/article_creator'
  # test only

  get 'static/gosearts_test'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/key_word.rb
class KeyWord < ApplicationRecord
    require 'date'
    has_many :articles, dependent: :destroy
    has_many :gosearts, dependent: :destroy
    has_many :bing_articles, dependent: :destroy
    has_many :factiva_articles, dependent: :destroy
    has_many :articleintern 
    has_many :posts, dependent: :destroy
    #after_initialize :initialize_keyword



    def has_new_article 
       if self.articles.count > 0  
           self.articles.each do |article|
              article_date= DateTime.parse(article.published)
              time_diff= (DateTime.now - article_date) * 24
              if time_diff < 72
                return true
              end
             end
       end
      false
       
    end

end
# article_date= DatTime.parse(article.published)
# time_diff= (DatTime.now - article_date) * 24
# if time_diff < 72
#  return true
# end

app/controllers/key_words_controller.rb
class KeyWordsController < ApplicationController
  before_action :set_key_word, only: %i[show edit update destroy]
  require 'csv'
  skip_before_action :verify_authenticity_token
  # GET /key_words or /key_words.json
  def index
    @key_words = KeyWord.all
    render json: @key_words
  end

  def keyword_posts
    id = params[:id]
    key_word = KeyWord.find(id)
  
    if params[:status] == "incoming" || params[:status].nil?
      posts = key_word.posts.where(category_label: nil)
    elsif params[:status] == "published"
      posts = key_word.posts.where(category_label: "published")
    elsif params[:status] == "shortlist"
      posts = key_word.posts.where(category_label: "shortlist")
    elsif params[:status] == "archived"
      posts = key_word.posts.where(category_label: "archived")
    else
      render json: { error: "Invalid status" }, status: :unprocessable_entity
      return
    end
  
    formatted_posts = posts.map do |post|
      {
        id: post.id,
        key_word_id: post.key_word_id,
        title: post.title,
        published: post.published,
        link: post.link,
        category_label: post.category_label,
        score: post.score,
        score_second: post.score_second,
        source: post.source,
        created_at: post.created_at,
        updated_at: post.updated_at,
        key_word: {
          key_word: key_word.key_word
        }
      }
    end
  
    render json: formatted_posts
  end

  # GET /key_words/1 or /key_words/1.json
  def show
    key_word_json = @key_word.as_json(include: %i[gosearts articles bing_articles])
    render json: key_word_json
  end

  # GET /key_words/new
  def new
    @key_word = KeyWord.new
  end

  # GET /key_words/1/edit
  def edit; end

  # POST /key_words or /key_words.json
  def create
    @key_word = KeyWord.new(key_word_params)

    respond_to do |format|
      if @key_word.save
        format.html { redirect_to key_word_url(@key_word), notice: 'Key word was successfully created.' }
        format.json { render :show, status: :created, location: @key_word }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @key_word.errors, status: :unprocessable_entity }
      end
    end
  end
  # import csv

  def import
    file = params[:file]
    return redirect_to key_words_path, notice: 'Only CSV please' unless file.content_type == 'text/csv'

    CsvImportKeyWordsService.new.call(file)

    redirect_to key_words_path, notice: 'Key words imported '
  end

  # PATCH/PUT /key_words/1 or /key_words/1.json
  def update
    respond_to do |format|
      if @key_word.update(key_word_params)
        format.html { redirect_to key_word_url(@key_word), notice: 'Key word was successfully updated.' }
        format.json { render :show, status: :ok, location: @key_word }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @key_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /key_words/1 or /key_words/1.json
  def destroy
    @key_word.destroy

    respond_to do |format|
      format.html { redirect_to key_words_url, notice: 'Key word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_key_word
    @key_word = KeyWord.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def key_word_params
    params.require(:key_word).permit(:key_word, :rss_url, :factiva, :file, :combined)
  end
end

app/helpers/key_words_helper.rb
module KeyWordsHelper
end

app/views/key_words/_form.html.erb
<%= form_with(model: key_word) do |form| %>
  <% if key_word.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(key_word.errors.count, "error") %> prohibited this key_word from being saved:</h2>

      <ul>
        <% key_word.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="card card-plain w-50">
      <div class="  mb-3" >
        <%= form.label "Keyword",class:"form-label" %>
        <%= form.text_area :key_word, class:"form-control",placeholder: ' put your key word',style:"border: 1px solid lightgray"  %>
      </div>

      <div class="mb-3">
        <%= form.label :rss_url, class:"form-label" %>
        <%= form.text_field :rss_url,class:"form-control",placeholder: 'Paste your rss feed here' ,style:"border: 1px solid lightgray"%>
      </div>

      <div class="">
        <%= form.label :is_factiva, class:"form-label" %>
        <%= form.check_box :factiva %>
      </div>
          <div class="">
        <%= form.label :combined, class:"form-label" %>
        <%= form.check_box :combined %>
      </div>
   
      <div class="text-center">
        <%= form.submit class:"btn btn-lg bg-gradient-primary btn-lg w-50 mt-4 mb-0" %>
      </div>
  </div>

 
<% end %>

app/views/key_words/_key_word.html.erb
    <tr id="<%= dom_id key_word  %>" >
        <td  >
           <div class="d-flex px-2 py-1">

                          <div class="d-flex flex-column justify-content-center">
                             <%= link_to key_word.key_word,  key_word%>
                             <p>Number of articles : <%=  key_word.articles.count %></p> 
          
                          </div>
                        </div>
                      </td>
                      <td>
                        <p class="text-xs font-weight-bold mb-0"><%=key_word.created_at %></p>
                
                      </td>
                      <td class="align-middle text-center text-sm">
                        <span class="badge badge-sm bg-gradient-success" ><%=link_to 'See ', key_word %></span>
                      </td>
                       
    </tr>

app/views/key_words/_switch_form.html.erb
<%= form_with(model: article, data: { switch_target: "submit" }) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



      <div>
    <%= form.label :posted, class:'switch' do %>
           <label class="switch">
               <%= form.check_box :posted,data: { switch_target: "input" }  %>
              <span class="slider round"></span> 
          </label>
      <%end%>
  
  </div>

  <div>
    <% form.submit 'Submit', class:'btn btn-alert',data: { switch_target: "submit" }  %>
  </div>
<% end %>

app/views/key_words/edit.html.erb
<h1>Editing keyword</h1>

<%= render "form", key_word: @key_word %>

<br>

<div>
  <%= link_to "Show this key word", @key_word %> |
  <%= link_to "Back to key words", key_words_path %>
</div>

app/views/key_words/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Keywords</h1>

<%= link_to "New key word", new_key_word_path,class:"badge badge-sm bg-gradient-success" %>
 <div class="container-fluid py-4">
      <div class='row'>
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <div class ="d-flex justify-content-around">
                <h6 class="text-white text-capitalize ps-3"> Keywords</h6>
                  <div>
                      <%= form_tag(key_words_path, method: "get", class: "search-form") do %>
                              <%= text_field_tag :search, params[:search], placeholder: "Search articles by name" %>
                          <%= submit_tag "Search", class: "btn btn-primary" %>
                      <% end %>
                </div>
                </div>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr >
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Key Word</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Created</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">See more</th>
         
                      <th class="text-secondary opacity-7"></th>
                    </tr>
                  </thead>
                  <tbody>
               <% @key_words.each do |key_word| %>
                <%= render key_word %>

                <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
</div>

app/views/key_words/new.html.erb
<h1>New keyword</h1>

<%= render "form", key_word: @key_word %>

<br>
<div>
 <%= form_with url: import_key_words_path, method: :post do |form| %>
 <%= form.file_field :file, accept: ".csv" %>
 <%= form.submit "Import"%>
 <%end%>

</div>
<div>
  <%= link_to "Back to key words", key_words_path %>
</div>

app/views/key_words/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%=@key_word.key_word%></h1>
<div class='row '>
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">All News</h6>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr >
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7  ">Title</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Related to</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Link</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Date</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Status</th>
                      <th class="text-secondary opacity-7"></th>
                    </tr>
                  </thead>
                  <tbody>
                  <%@key_word.articles.each do |article | %>
                  <%= render article%>
                  <%end%>   
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>


<div>
  <%= link_to "Edit this key word", edit_key_word_path(@key_word) %> |
  <%= link_to "Back to key words", key_words_path %>

  <%= button_to "Destroy this key word", @key_word, method: :delete %>
</div>