config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :summaries
  resources :articleinterns
  resources :bing_articles
  resources :gosearts
  resources :media
  resources :factiva_articles
  resources :articles
  resources :key_words do
    get 'keyword_posts/:id', to: 'key_words#keyword_posts', as: 'keyword_posts'
    collection do
      post :import
    end
  end
  root 'static#home'
  devise_for :users

  get 'static/test_post'
  get 'static/test'
  get 'static/test_webflow'
  post 'static/test_webhook'
  get 'static/scraper'
  get 'static/gosearts'
  get 'static/bing_news'
  get 'static/dashboard'
  get 'static/articleintern'
  get 'static/analyzer'
  get 'static/analyzer_new'
  get 'static/keyword_list'
  get 'static/article_creator'
  # test only

  get 'static/gosearts_test'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_aside.html.erb
      <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">

  <div class="sidenav-header">
    <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
    <a class="navbar-brand m-0" href=" https://demos.creative-tim.com/material-dashboard/pages/dashboard " target="_blank">
      <img src="./assets/img/logo-ct.png" class="navbar-brand-img h-100" alt="main_logo">
      <span class="ms-1 font-weight-bold text-white">Material Dashboard 2</span>
    </a>
  </div>


  <hr class="horizontal light mt-0 mb-2">

  <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
    <ul class="navbar-nav">
<li class="nav-item">
  <a class="nav-link text-white " href="./dashboard.html">
    
      <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
        <i class="material-icons opacity-10">dashboard</i>
      </div>
    
    <span class="nav-link-text ms-1">Dashboard</span>
  </a>
</li>

  
<li class="nav-item">
  <a class="nav-link text-white " href="./tables.html">
    
      <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
        <i class="material-icons opacity-10">table_view</i>
      </div>
    
    <span class="nav-link-text ms-1">Tables</span>
  </a>
</li>

  
<li class="nav-item">
  <a class="nav-link text-white " href="./billing.html">
    
      <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
        <i class="material-icons opacity-10">receipt_long</i>
      </div>
    
    <span class="nav-link-text ms-1">Billing</span>
  </a>
</li>

  
<li class="nav-item">
  <a class="nav-link text-white " href="./virtual-reality.html">
    
      <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
        <i class="material-icons opacity-10">view_in_ar</i>
      </div>
    
    <span class="nav-link-text ms-1">Virtual Reality</span>
  </a>
</li>

  
<li class="nav-item">
  <a class="nav-link text-white " href="./rtl.html">
    
      <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
        <i class="material-icons opacity-10">format_textdirection_r_to_l</i>
      </div>
    
    <span class="nav-link-text ms-1">RTL</span>
  </a>
</li>

  
<li class="nav-item">
  <a class="nav-link text-white " href="./notifications.html">
    
      <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
        <i class="material-icons opacity-10">notifications</i>
      </div>
    
    <span class="nav-link-text ms-1">Notifications</span>
  </a>
</li>

  
    <li class="nav-item mt-3">
      <h6 class="ps-4 ms-2 text-uppercase text-xs text-white font-weight-bolder opacity-8">Account pages</h6>
    </li>
  
<li class="nav-item">
  <a class="nav-link text-white " href="./profile.html">
    
      <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
        <i class="material-icons opacity-10">person</i>
      </div>
    
    <span class="nav-link-text ms-1">Profile</span>
  </a>
</li>

  
<li class="nav-item">
  <a class="nav-link text-white " href="./sign-in.html">
    
      <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
        <i class="material-icons opacity-10">login</i>
      </div>
    
    <span class="nav-link-text ms-1">Sign In</span>
  </a>
</li> 
<li class="nav-item">
  <a class="nav-link text-white " href="./sign-up.html">
    
      <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
        <i class="material-icons opacity-10">assignment</i>
      </div>  
    <span class="nav-link-text ms-1">Sign Up</span>
  </a>
</li>
    </ul>
  </div>
  <div class="sidenav-footer position-absolute w-100 bottom-0 ">
    <div class="mx-3">
      <a class="btn bg-gradient-primary mt-4 w-100" href="https://www.creative-tim.com/product/material-dashboard-pro?ref=sidebarfree" type="button">Violet button</a>
    </div> 
  </div>
</aside>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <%=link_to 'Home',root_path,class:"navbar-brand"%>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
  
      <li class="nav-item">
      </li>
        <li class="nav-item">
        <%=link_to 'Keywords',key_words_path,class:"navbar-brand"%>
      </li>
     
       <li class="nav-item">
        <%=link_to 'Google alerts ',articles_path,class:"navbar-brand"%>
      </li>
      <li class="nav-item">
        <%=link_to 'Factiva  alerts ',factiva_articles_path,class:"navbar-brand"%>
      </li>
      <% if current_user %> 
         <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, method: :delete,class:"navbar-brand", style:'color : red;' %> 
         </li>
      <% else %>
        <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path , class:"navbar-brand", style: 'color : green;' %> 
         </li>
<% end %>
    </ul>
    <%=link_to 'Google Alerts Refresh', static_test_post_path,class:" btn bg-gradient-primary mt-4  ",style:"margin-right:10px;"%>
    <%=link_to 'Factiva Alerts Refresh', static_test_path,class:" btn bg-gradient-success mt-4  ",style:"margin-right:10px;"%>
 
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Muses Community Jameel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Font Awesome Icons -->
   <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
<!-- Material Icons -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<!-- CSS Files -->
  </head>

  <body class="g-sidenav-show  bg-gray-100">
  <div class='container'>
  <% if current_user %>
  <%= render 'layouts/navbar' %>
  <%end%>
    </div>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>